# numpy array

In [1]:
import numpy as np

In [2]:
#creating an array
arr=np.array((1,2,3,4,5))

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
#data type of an array

arr=np.array([1,2,3,4,5],dtype=float)

In [5]:
arr

array([1., 2., 3., 4., 5.])

In [6]:
arr=np.array([],dtype='S')

In [7]:
arr=np.arange(10,40,2)

In [8]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [9]:
np.insert(arr,5,int(40))

array([10, 12, 14, 16, 18, 40, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [10]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [11]:
arr=np.append(arr,50)

In [12]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 50])

In [13]:
# 2 dimensional array (matrix)

In [14]:
mat=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])

In [15]:
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print(f"{mat}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
#wap to add elements of two lists

In [18]:
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

3.6075282096862793


In [19]:
arr1=np.arange(10000000)
arr2=np.arange(10000000,20000000)
import time
start=time.time()
arr4=arr1+arr2
print(time.time()-start)

0.015623331069946289


In [20]:
arr3

NameError: name 'arr3' is not defined

In [ ]:
arr4

In [ ]:
c

In [ ]:
mat

In [ ]:
mat[1,1]

In [ ]:
mat[1]

In [ ]:
# printing columns of matrix
j=1
for i in range(3):
    print(mat[i,j])

In [ ]:
d3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [ ]:
print(d3)

In [ ]:
d3[1,1]

In [ ]:
d3[1]

In [ ]:
d3[1,1,2]

In [ ]:
# task:
# 1> searching an element in an array
# 2> find largest element in an array
# 3> finding smallest number in an array
# 4> reversing an array
# 5> rotating an array from Kth position


In [ ]:
#searching an element in an array
import numpy as np
arr1=np.array([1,2,3,4,4,45,56,7])
x=np.where(45)
print(x)

In [ ]:
# finding largest elemnent in array
x=np.array(max(arr1))
print(x)

In [ ]:
#finding smallest number in an array
x=np.array(min(arr1))
print(x)

In [ ]:
#reversing an array
x=arr1[::-1]
print(x)

In [24]:
#rotating an array about kth position



TypeError: only integer scalar arrays can be converted to a scalar index